apiVersion: component.opensearch.crossplane.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: opensearch/v1alpha1/componenttemplate
  labels:
    testing.upbound.io/example-name: template1
  name: template1
spec:
  forProvider:
    name: template1
    body: |
      {
        "template": {
          "settings": {
            "number_of_shards": 1
          },
          "mappings": {
            "_source": {
              "enabled": false
            },
            "properties": {
              "host_name": {
                "type": "keyword"
              },
              "created_at": {
                "type": "date",
                "format": "EEE MMM dd HH:mm:ss Z yyyy"
              }
            }
          }
        }
      }
