apiVersion: index.opensearch.crossplane.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: opensearch/v1alpha1/indextemplate
  labels:
    testing.upbound.io/example-name: writer
  name: writer
spec:
  forProvider:
    name: indextemplate
    body: |
      {
        "index_patterns": [
          "logs-2020-01-*"
        ],
        "template": {
          "aliases": {
            "my_logs": {}
          },
          "settings": {
            "number_of_shards": 2,
            "number_of_replicas": 1
          },
          "mappings": {
            "properties": {
              "timestamp": {
                "type": "date",
                "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
              },
              "value": {
                "type": "double"
              }
            }
          }
        }
      }
